language: python

sudo: required

env:
- N=00
- N=01
- N=02
- N=03
- N=04
- N=05
- N=06
- N=07
- N=08
- N=09
- N=10
- N=11
- N=12
- N=13
- N=14
- N=15
- N=16
- N=17
- N=18
- N=19

install: echo install eh
script: echo script eh
